buildVariable: false
familyName: Noto Sans Tifinagh
googleFonts: true
includeSubsets:
- from: Noto Sans
  name: GF_Latin_Core
interpolate: true
recipeProvider: noto
sources:
- NotoSansTifinagh.glyphs
