buildVariable: false
interpolate: true # To build the variant glyphs
familyName: Noto Sans Tifinagh
googleFonts: true
includeSubsets:
- from: Noto Sans
  name: GF_Latin_Core
sources:
- NotoSansTifinagh.glyphs
